version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=chick
      - POSTGRESQL_PASSWORD=chick
      - POSTGRESQL_DATABASE=chick
  redis:
    image: redis:latest
    ports:
      - 6379:6379
